# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flut',
            name='user',
        ),
        migrations.AddField(
            model_name='flut',
            name='user_name',
            field=models.TextField(default='Flutter User', max_length=20),
        ),
        migrations.AlterField(
            model_name='flut',
            name='flut_text',
            field=models.TextField(default='Flitter flut flit fleet flot flippidy fleek fleeb, flibber flabber flip flop.', max_length=140),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
