# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0002_auto_20160519_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='flut',
            name='time_stamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
