# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0003_flut_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flut',
            name='time_stamp',
            field=models.DateTimeField(),
        ),
    ]
