# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0004_auto_20160519_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flut',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
